self.keyboard.slowPress("e")
sleep(0.52)
self.keyboard.keyDown("w")
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
sleep(5.35)
self.keyboard.keyUp("w")
time.sleep(2.2)
self.keyboard.walk("w",2.48)
self.keyboard.walk("a",1.3)
self.keyboard.walk("w",0.1)
self.keyboard.walk("a",0.2)
self.useItemInInventory("gumdrops")
time.sleep(2)
self.keyboard.walk("w",2.5)

