
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(6.5)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(4)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(10)
for i in range(width):
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(10 * size)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(1)
	for i in range(4):
		self.keyboard.keyUp(tcfbkey, False)
		self.keyboard.keyDown(afclrkey, False)
		self.keyboard.tileWait(8 * size - 1)
		self.keyboard.keyUp(afclrkey, False)
		self.keyboard.keyDown(tcfbkey, False)
		self.keyboard.tileWait(1)
		self.keyboard.keyUp(tcfbkey, False)
		self.keyboard.keyDown(tclrkey, False)
		self.keyboard.tileWait(8 * size - 1)
		self.keyboard.keyUp(tclrkey, False)
		self.keyboard.keyDown(tcfbkey, False)
		self.keyboard.tileWait(1)
self.keyboard.keyUp(tcfbkey, False)