
self.keyboard.press(",")
self.keyboard.press(",")
self.keyboard.slowPress("e")
self.keyboard.keyDown("w")
sleep(1.15)
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
time.sleep(2.5)
self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
self.keyboard.slowPress(".")
self.keyboard.slowPress(".")
sleep(1.6)
self.keyboard.slowPress("space")
self.keyboard.keyUp("w")
self.keyboard.press(",")
self.keyboard.press(",")
sleep(0.6)
    
