self.keyboard.press(".")
self.keyboard.press(".")
self.keyboard.press(".")
self.keyboard.walk("w",10)
self.keyboard.press(",")
self.keyboard.press(",")
self.keyboard.press(",")
self.keyboard.walk("d",6)
self.keyboard.walk("w",6)
self.keyboard.walk("a",1.2)
self.keyboard.walk("w",6)
self.keyboard.walk("d",3)
self.keyboard.walk("s",0.6)

