self.keyboard.walk("s",3)
time.sleep(0.5)
self.keyboard.walk("d",7,False)
self.keyboard.keyDown("w")
time.sleep(7)
self.keyboard.press("space")
time.sleep(2)
self.keyboard.press("space")
time.sleep(2.5)
self.keyboard.press("space")
time.sleep(2.5)
self.keyboard.keyUp("w")
self.keyboard.walk("s",0.35)
self.keyboard.walk("d",2, False)
self.keyboard.walk("w",0.8)
self.keyboard.multiWalk(["s","a"], 0.9)
self.keyboard.walk("d",0.25)
