self.keyboard.walk("d",5)
self.keyboard.walk("s",7)
self.keyboard.press('space')
self.keyboard.keyDown("a")
time.sleep(12*28/ws)
self.keyboard.keyUp("a")
self.keyboard.walk("w",8)
self.keyboard.walk("d",4)
self.keyboard.walk("s",1)
self.keyboard.walk("w",1.2)
self.keyboard.slowPress("space")
time.sleep(0.1)
self.keyboard.slowPress("space")
time.sleep(8)
self.keyboard.walk("w",13)
self.keyboard.walk("s",0.4)
self.keyboard.walk("d",5)
self.keyboard.walk("w",1)
self.keyboard.walk("s",0.55)

    
