self.keyboard.walk("d",5)
self.keyboard.walk("s",7)
self.keyboard.press('space')
self.keyboard.walk("a",11)
self.keyboard.walk("w",6)
self.keyboard.slowPress("space")
time.sleep(0.9)
self.keyboard.walk("w",0.1, False)
time.sleep(0.5)
self.keyboard.slowPress("space")
time.sleep(0.1)
self.keyboard.slowPress("space")
time.sleep(8.5)
self.keyboard.walk("d",5)
self.keyboard.walk("w",1)
self.keyboard.walk("s",0.55)

    
