self.keyboard.KeyDown("a")
self.keyboard.KeyDown("s")
time.sleep(5)
self.keyboard.KeyUp("a")
self.keyboard.KeyUp("s")
self.keyboard.KeyDown("w")
time.sleep(6.5)
self.keyboard.KeyUp("w")
self.keyboard.walk("a", 3, False)
self.keyboard.walk("d", 2, False)
self.runPath(f"field_to_hive/sunflower")