self.keyboard.walk("d",3, False)
self.keyboard.walk("w",3.5, False)
self.keyboard.press("shift")
self.keyboard.walk("a",4.5, False)
self.keyboard.press("shift")
self.keyboard.walk("w",6, False)
self.keyboard.walk("s",0.35)
self.keyboard.walk("d",1.5, False)
self.keyboard.walk("w",0.45, False)
self.keyboard.multiWalk(["s","a"], 0.9)
self.keyboard.walk("d",0.25)