self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
self.keyboard.slowPress("e")
self.keyboard.keyDownrd.keyDown("w")
sleep(0.4)
self.keyboard.slowPress("space")
self.keyboard.slowPress("space")
sleep(0.5)
self.keyboard.slowPress(",")
self.keyboard.slowPress(",")
self.keyboard.slowPress(".")
self.keyboard.slowPress(".")
sleep(0.2)
self.keyboard.keyUp("w")
self.keyboard.slowPress("space")

    
