exec(open("./paths/field_blue flower.py").read())
move.apkey("space")
self.keyboard.walk("s",3)
self.keyboard.walk("a",5)
self.keyboard.walk("w",1.5)
self.keyboard.walk('d',0.1)
self.keyboard.slowPress(",")
self.keyboard.walk("w",7)
self.keyboard.slowPress(",")
