move.press(",")
move.press("e")
pag.keyDown("w")
time.sleep(0.12)
move.press("space")
move.press("space")
time.sleep(3.5)
pag.keyUp("w")
move.press("space")
time.sleep(0.5)
move.hold("w",3.5)
move.hold("d",2.5)
move.hold("s",1.5)
    
