#Ahk code converted by Existance Macro


self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(7)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(9)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(3)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(3)
self.keyboard.keyUp(tclrkey, False)
for i in range(width):
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(10)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(5)
	self.keyboard.keyUp(tcfbkey, False)
	for i in range(2):
		self.keyboard.keyDown(afclrkey, False)
		self.keyboard.tileWait(2)
		self.keyboard.keyUp(afclrkey, False)
		self.keyboard.keyDown(afcfbkey, False)
		self.keyboard.tileWait(3)
		self.keyboard.keyUp(afcfbkey, False)
		self.keyboard.keyDown(afclrkey, False)
		self.keyboard.tileWait(2)
		self.keyboard.keyUp(afclrkey, False)
		self.keyboard.keyDown(tcfbkey, False)
		self.keyboard.tileWait(3)
		self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(2)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(5)
	self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(7)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(9)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(3)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(3)
self.keyboard.keyUp(tclrkey, False)
for i in range(width):
	for i in range(2):
		self.keyboard.keyDown(tclrkey, False)
		self.keyboard.tileWait(2)
		self.keyboard.keyUp(tclrkey, False)
		self.keyboard.keyDown(tcfbkey, False)
		self.keyboard.tileWait(3)
		self.keyboard.keyUp(tcfbkey, False)
		self.keyboard.keyDown(tclrkey, False)
		self.keyboard.tileWait(2)
		self.keyboard.keyUp(tclrkey, False)
		self.keyboard.keyDown(afcfbkey, False)
		self.keyboard.tileWait(3)
		self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(2)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(5)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(10)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(5)
	self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(afclrkey, False)
self.keyboard.tileWait(7)
self.keyboard.keyUp(afclrkey, False)
self.keyboard.keyDown(afcfbkey, False)
self.keyboard.tileWait(9)
self.keyboard.keyUp(afcfbkey, False)
self.keyboard.keyDown(tcfbkey, False)
self.keyboard.tileWait(8)
self.keyboard.keyUp(tcfbkey, False)
self.keyboard.keyDown(tclrkey, False)
self.keyboard.tileWait(1.5)
self.keyboard.keyUp(tclrkey, False)
self.keyboard.press(rotleft)
for i in range(width):
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(6)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(2)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(4)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(2)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(4)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(tcfbkey, False)
	self.keyboard.tileWait(2)
	self.keyboard.keyUp(tcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(6)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(2)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(tclrkey, False)
	self.keyboard.tileWait(4)
	self.keyboard.keyUp(tclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(2)
	self.keyboard.keyUp(afcfbkey, False)
	self.keyboard.keyDown(afclrkey, False)
	self.keyboard.tileWait(4)
	self.keyboard.keyUp(afclrkey, False)
	self.keyboard.keyDown(afcfbkey, False)
	self.keyboard.tileWait(2)
	self.keyboard.keyUp(afcfbkey, False)
self.keyboard.press(rotright)
#miku-tideshift
#@nointerrupt
#made by denzツ / denz_777